name: Build and Test

on:
  push:
    branches-ignore:
      - master
      - main
  pull_request_target:
    branches-ignore:
      - main
      - master

env:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'    
        
    - name: Setup Tactile NuGet Source
      run: dotnet nuget add source "${{ secrets.NUGET_SOURCE_URL }}" --name "github" --username USERNAME --password ${{ secrets.NUGET_API_TOKEN }} --store-password-in-clear-text

    - name: Restore dependencies
      run: dotnet restore

    - name: Build Project
      run: dotnet build --configuration Release

    - name: Install trx2junit
      run: dotnet tool install --global trx2junit

    - name: Run tests
      run: dotnet test --no-restore -l "trx;LogFileName=test-output.trx"
    
    - name: Move test files to folder
      if: always()
      run: |
        mkdir -p ./test-results
        find . -name "test-output.trx" -exec mv {} ./test-results/test-result.trx \;
        trx2junit ./test-results/test-result.trx --output ./test-results/

    - name: Archive test results
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: test-results
        path: ./test-results/