name: Repository Setup on Creation

on: create

jobs:
  setup-repo:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'repository'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Replace Templated Text in File Contents
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F 'build-plugins.' '{print $2}')
          FORMATTED_NAME=$(echo "$REPO_NAME" |  awk -F '-' '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1' OFS="")
          find . -type f ! -path '*/\.*' -exec sed -i "s/PLUGIN_NAME/$FORMATTED_NAME/g" {} +

      - name: Rename Files
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F 'build-plugins.' '{print $2}')
          FORMATTED_NAME=$(echo "$REPO_NAME" |  awk -F '-' '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1' OFS="")
          find . -type f -name '*PLUGIN_NAME*' ! -path '*/\.*' | while read file; do
            new_file=$(echo "$file" | sed "s/PLUGIN_NAME/$FORMATTED_NAME/g")
            mv "$file" "$new_file"
            echo "Renamed file $file to $new_file"
          done

      - name: "Echo"
        run: |
          echo "GITHUB_REPOSITORY: $GITHUB_REPOSITORY"
          echo "REPO_NAME: $REPO_NAME"
          echo "FORMATTED_NAME: $FORMATTED_NAME"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Replace templated text with actual values"
          git push origin HEAD:master  # Replace 'main' with 'master' if your default branch is named 'master'
