name: Repository Setup on Creation

on: push

jobs:
  setup-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Replace Templated Text in File Contents
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F 'build-plugins.' '{print $2}')
          FORMATTED_NAME=$(echo "$REPO_NAME" |  awk -F '-' '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1' OFS="")
          find . -type f ! -path '*/\.*' -exec sed -i "s/PLUGIN_NAME/$FORMATTED_NAME/g" {} +

      - name: Rename Files
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F 'build-plugins.' '{print $2}')
          FORMATTED_NAME=$(echo "$REPO_NAME" |  awk -F '-' '{for(i=1;i<=NF;i++){$i=toupper(substr($i,1,1)) substr($i,2)}}1' OFS="")
          find . -type f -name '*PLUGIN_NAME*' ! -path '*/\.*' | while read file; do
            new_file=$(echo "$file" | sed "s/PLUGIN_NAME/$FORMATTED_NAME/g")
            mv "$file" "$new_file"
            echo "Renamed file $file to $new_file"
          done

      - name: Delete Setup Workflow
        run: rm .github/workflows/repo_setup.yml

      - name: Follow Project on CircleCI
        env:
          CIRCLE_TOKEN: ${{ secrets.CIRCLE_CI_ADMIN_TOKEN_OLD }}
        run: |
          FOLLOW_ENDPOINT="https://circleci.com/api/v1.1/project/github/${GITHUB_REPOSITORY}/follow"

          response=$(curl -X POST $FOLLOW_ENDPOINT \
                     -H "Circle-Token: $CIRCLE_TOKEN" \
                     -H "Content-Type: application/json" \
                     -d '{"first_build": "true"}')

          echo "Response from CircleCI: $response"

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "[skip ci] Project Setup by Github Action"
          git push origin HEAD:master
