name: Repository Setup on Creation

on:
  create

jobs:
  setup-repo:
    runs-on: ubuntu-latest
    if: github.event.ref_type == 'repository'
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Replace Templated Text
        run: |
          REPO_NAME=$(echo $GITHUB_REPOSITORY | awk -F'-' '{print $NF}')
          FORMATTED_NAME=$(echo $REPO_NAME | sed 's/-/ /g' | awk '{for(i=1;i<=NF;i++)sub(/./,toupper(substr($i,1,1)),$i)}1' | tr -d ' ')
          find . -type f ! -path '*/\.*' -exec sed -i "s/PLUGIN_NAME/$FORMATTED_NAME/g" {} +

      - name: Commit and Push Changes
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add .
          git commit -m "Replace templated text with actual values"
          git push origin HEAD:master  # Replace 'main' with 'master' if your default branch is named 'master'